[package]
name = "calc"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.36.1", features = ["default_fonts", "glow", "persistence"] }
num-complex = "0.4.6"

[profile.release]  
opt-level = 2 
codegen-units = 1  
lto = true  
panic = "abort"  
  
[profile.dev.package."*"]  
opt-level = 2
